# Generated by Django 4.2.3 on 2023-07-26 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Понятный для')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Понятный для')),
                ('description', models.CharField(max_length=500, verbose_name='Описание фильма')),
                ('poster', models.ImageField(upload_to='movie_poster/', verbose_name='Постер фильма')),
                ('trailer', models.URLField(verbose_name='Трейлер')),
                ('movie', models.FileField(upload_to='movie_video/', verbose_name='Посмотреть фильм')),
                ('year', models.DateField(default=0, verbose_name='Дата выпуска')),
                ('running_time', models.CharField(max_length=10, verbose_name='Длительность фильма')),
                ('country', models.CharField(max_length=200, verbose_name='Страна')),
                ('directors', models.CharField(max_length=555, verbose_name='Режиссёры')),
                ('actors', models.CharField(blank=True, max_length=50000, null=True, verbose_name='Актёры')),
                ('genres', models.CharField(max_length=255, verbose_name='Жанры')),
                ('rating', models.FloatField(default=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
